esphome:
  name: vibration-sensor
  friendly_name: Vibration Sensor
esp8266:
  board: d1_mini
logger:
api:
  encryption:
    key: !secret api_key
ota:
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Vibration-Sensor"
    password: !secret ap_password
captive_portal:

# Sensor Configuration
binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode:
        input: true
        pullup: false
    name: "Vibration"
    device_class: vibration
    filters:
      - delayed_on: !lambda |-
          return id(DELAY_ON).state;
      - delayed_off: !lambda |-
          return id(DELAY_OFF).state;

# Dynamic adjustment
number:
  - platform: template
    name: "Delay ON"
    id: DELAY_ON
    min_value: 0
    max_value: 1000
    mode: slider
    device_class: duration
    entity_category: config
    unit_of_measurement: ms
    icon: mdi:timer
    step: 1
    optimistic: True
    initial_value: 10
    restore_value: True
  - platform: template
    name: "Delay OFF"
    id: DELAY_OFF
    min_value: 0
    max_value: 6000
    mode: slider
    device_class: duration
    entity_category: config
    unit_of_measurement: ms
    icon: mdi:timer-off
    step: 10
    optimistic: True
    initial_value: 300
    restore_value: True
